[build]
  command = "npm run build"
  publish = "dist"

[build.processing]
  skip_node_modules = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "upgrade-insecure-requests"
